### PR TITLE
Add travis script

### PR DESCRIPTION
**Pull request by fintelia**

### CODE REVIEW

**Comment by jonhoo** [comment]
https://github.com/crate-ci/azure-pipelines :wink: 
See for example: https://github.com/jonhoo/tracing-timing/blob/master/azure-pipelines.yml

**Comment by fintelia** [comment]
Do you recommend that instead of/in addition to travis?

**Comment by jonhoo** [comment]
I've started switching all my things over to that (I'm one of the maintainers)

**Comment by fintelia** [comment]
Probably. I'm going to merge this, publish a new version and then try cleaning things up.

**Pull request merged**
